apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: nexis
  labels:
    app: nexis
    component: backend
type: Opaque
stringData:
  url: mongodb://mongodb.nexis.svc.cluster.local:27017/financial_agent_v2
